[package]
name = "pe25"
version = "0.1.0"
authors = ["Peter Lacey-Bordeaux <placey@indeed.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.2.3"
num-traits = "0.2.7"
